spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  devtools:
    restart:
      enabled: ${DEVTOOLS_IS_DEV_MODE}
      additional-paths: src

line:
  frontend-url: ${LINE_WEBAPP_URL}
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    channel-secret: ${LINE_BOT_CHANNEL_SECRET}
    handler:
      path: /callback
  token:
    token-url: ${LINE_WEBAPP_TOKEN_URL}
    channel-id: ${LINE_WEBAPP_CHANNEL_ID}
    channel-secret: ${LINE_WEBAPP_CHANNEL_SECRET}
    grant-type: ${LINE_WEBAPP_GRANT_TYPE}
    redirect-uri: ${LINE_WEBAPP_REDIRECT_URI}
